/**
 * Workflow Departamental API
 *
 * Contact: soporte@workflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpContext 
        }       from '@angular/common/http';
import { Observable }                                        from 'rxjs';
import { OpenApiHttpParams, QueryParamStyle } from '../query.params';

// @ts-ignore
import { ApiResponseListSolicitudResponse } from '../model/apiResponseListSolicitudResponse';
// @ts-ignore
import { ApiResponseMapStringObject } from '../model/apiResponseMapStringObject';
// @ts-ignore
import { ApiResponseSolicitudResponse } from '../model/apiResponseSolicitudResponse';
// @ts-ignore
import { AsignarUsuarioRequest } from '../model/asignarUsuarioRequest';
// @ts-ignore
import { CambiarEstadoRequest } from '../model/cambiarEstadoRequest';
// @ts-ignore
import { CrearSolicitudRequest } from '../model/crearSolicitudRequest';
// @ts-ignore
import { ReasignarDepartamentoRequest } from '../model/reasignarDepartamentoRequest';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class WorkflowDepartamentalService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * Asignar Usuario a Solicitud
     * Asigna directamente a la persona encargada de trabajar la solicitud.
     * @endpoint patch /api/v1/workflows/{id}/asignar
     * @param id 
     * @param asignarUsuarioRequest 
     * @param xUsuario 
     * @param xRol 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public asignarUsuario(id: string, asignarUsuarioRequest: AsignarUsuarioRequest, xUsuario?: string, xRol?: 'SOLICITANTE' | 'REVISOR' | 'ADMINISTRADOR', observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<ApiResponseSolicitudResponse>;
    public asignarUsuario(id: string, asignarUsuarioRequest: AsignarUsuarioRequest, xUsuario?: string, xRol?: 'SOLICITANTE' | 'REVISOR' | 'ADMINISTRADOR', observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ApiResponseSolicitudResponse>>;
    public asignarUsuario(id: string, asignarUsuarioRequest: AsignarUsuarioRequest, xUsuario?: string, xRol?: 'SOLICITANTE' | 'REVISOR' | 'ADMINISTRADOR', observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ApiResponseSolicitudResponse>>;
    public asignarUsuario(id: string, asignarUsuarioRequest: AsignarUsuarioRequest, xUsuario?: string, xRol?: 'SOLICITANTE' | 'REVISOR' | 'ADMINISTRADOR', observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling asignarUsuario.');
        }
        if (asignarUsuarioRequest === null || asignarUsuarioRequest === undefined) {
            throw new Error('Required parameter asignarUsuarioRequest was null or undefined when calling asignarUsuario.');
        }

        let localVarHeaders = this.defaultHeaders;
        if (xUsuario !== undefined && xUsuario !== null) {
            localVarHeaders = localVarHeaders.set('X-Usuario', String(xUsuario));
        }
        if (xRol !== undefined && xRol !== null) {
            localVarHeaders = localVarHeaders.set('X-Rol', String(xRol));
        }

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/workflows/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/asignar`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ApiResponseSolicitudResponse>('patch', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: asignarUsuarioRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Busqueda global parcial
     * Busca y retorna las solicitudes basándose en coincidencias parciales del Título.
     * @endpoint get /api/v1/workflows/buscar
     * @param titulo 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public buscarPorTitulo(titulo: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<ApiResponseListSolicitudResponse>;
    public buscarPorTitulo(titulo: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ApiResponseListSolicitudResponse>>;
    public buscarPorTitulo(titulo: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ApiResponseListSolicitudResponse>>;
    public buscarPorTitulo(titulo: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (titulo === null || titulo === undefined) {
            throw new Error('Required parameter titulo was null or undefined when calling buscarPorTitulo.');
        }

        let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

        localVarQueryParameters = this.addToHttpParams(
            localVarQueryParameters,
            'titulo',
            <any>titulo,
            QueryParamStyle.Form,
            true,
        );


        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/workflows/buscar`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ApiResponseListSolicitudResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                params: localVarQueryParameters.toHttpParams(),
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Actualizar estado / Aprobar / Rechazar
     * Principal operación del Revisor. Permite mover la solicitud dentro del flujo válido.
     * @endpoint patch /api/v1/workflows/{id}/estado
     * @param id 
     * @param cambiarEstadoRequest 
     * @param xUsuario 
     * @param xRol 
     * @param xDepartamento 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public cambiarEstado(id: string, cambiarEstadoRequest: CambiarEstadoRequest, xUsuario?: string, xRol?: 'SOLICITANTE' | 'REVISOR' | 'ADMINISTRADOR', xDepartamento?: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<ApiResponseSolicitudResponse>;
    public cambiarEstado(id: string, cambiarEstadoRequest: CambiarEstadoRequest, xUsuario?: string, xRol?: 'SOLICITANTE' | 'REVISOR' | 'ADMINISTRADOR', xDepartamento?: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ApiResponseSolicitudResponse>>;
    public cambiarEstado(id: string, cambiarEstadoRequest: CambiarEstadoRequest, xUsuario?: string, xRol?: 'SOLICITANTE' | 'REVISOR' | 'ADMINISTRADOR', xDepartamento?: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ApiResponseSolicitudResponse>>;
    public cambiarEstado(id: string, cambiarEstadoRequest: CambiarEstadoRequest, xUsuario?: string, xRol?: 'SOLICITANTE' | 'REVISOR' | 'ADMINISTRADOR', xDepartamento?: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling cambiarEstado.');
        }
        if (cambiarEstadoRequest === null || cambiarEstadoRequest === undefined) {
            throw new Error('Required parameter cambiarEstadoRequest was null or undefined when calling cambiarEstado.');
        }

        let localVarHeaders = this.defaultHeaders;
        if (xUsuario !== undefined && xUsuario !== null) {
            localVarHeaders = localVarHeaders.set('X-Usuario', String(xUsuario));
        }
        if (xRol !== undefined && xRol !== null) {
            localVarHeaders = localVarHeaders.set('X-Rol', String(xRol));
        }
        if (xDepartamento !== undefined && xDepartamento !== null) {
            localVarHeaders = localVarHeaders.set('X-Departamento', String(xDepartamento));
        }

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/workflows/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/estado`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ApiResponseSolicitudResponse>('patch', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: cambiarEstadoRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Crear nueva solicitud
     * Permite a un SOLICITANTE iniciar un nuevo trámite/solicitud en un departamento específico.
     * @endpoint post /api/v1/workflows
     * @param crearSolicitudRequest 
     * @param xUsuario 
     * @param xRol 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public crearSolicitud(crearSolicitudRequest: CrearSolicitudRequest, xUsuario?: string, xRol?: 'SOLICITANTE' | 'REVISOR' | 'ADMINISTRADOR', observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<ApiResponseSolicitudResponse>;
    public crearSolicitud(crearSolicitudRequest: CrearSolicitudRequest, xUsuario?: string, xRol?: 'SOLICITANTE' | 'REVISOR' | 'ADMINISTRADOR', observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ApiResponseSolicitudResponse>>;
    public crearSolicitud(crearSolicitudRequest: CrearSolicitudRequest, xUsuario?: string, xRol?: 'SOLICITANTE' | 'REVISOR' | 'ADMINISTRADOR', observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ApiResponseSolicitudResponse>>;
    public crearSolicitud(crearSolicitudRequest: CrearSolicitudRequest, xUsuario?: string, xRol?: 'SOLICITANTE' | 'REVISOR' | 'ADMINISTRADOR', observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (crearSolicitudRequest === null || crearSolicitudRequest === undefined) {
            throw new Error('Required parameter crearSolicitudRequest was null or undefined when calling crearSolicitud.');
        }

        let localVarHeaders = this.defaultHeaders;
        if (xUsuario !== undefined && xUsuario !== null) {
            localVarHeaders = localVarHeaders.set('X-Usuario', String(xUsuario));
        }
        if (xRol !== undefined && xRol !== null) {
            localVarHeaders = localVarHeaders.set('X-Rol', String(xRol));
        }

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/workflows`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ApiResponseSolicitudResponse>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: crearSolicitudRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Listar por departamento
     * Devuelve todas las solicitudes que actualmente residen en el flujo de un departamento.
     * @endpoint get /api/v1/workflows/departamento/{nombre}
     * @param nombre 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public listarPorDepartamento(nombre: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<ApiResponseListSolicitudResponse>;
    public listarPorDepartamento(nombre: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ApiResponseListSolicitudResponse>>;
    public listarPorDepartamento(nombre: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ApiResponseListSolicitudResponse>>;
    public listarPorDepartamento(nombre: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (nombre === null || nombre === undefined) {
            throw new Error('Required parameter nombre was null or undefined when calling listarPorDepartamento.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/workflows/departamento/${this.configuration.encodeParam({name: "nombre", value: nombre, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ApiResponseListSolicitudResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Filtrar por departamento y estado
     * Combinación para encontrar, por ejemplo, solicitudes \&#39;PENDIENTES\&#39; en el depto de \&#39;Sistemas\&#39;.
     * @endpoint get /api/v1/workflows/departamento/{nombre}/estado/{estado}
     * @param nombre 
     * @param estado 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public listarPorDepartamentoYEstado(nombre: string, estado: 'PENDIENTE' | 'EN_REVISION' | 'APROBADO' | 'RECHAZADO', observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<ApiResponseListSolicitudResponse>;
    public listarPorDepartamentoYEstado(nombre: string, estado: 'PENDIENTE' | 'EN_REVISION' | 'APROBADO' | 'RECHAZADO', observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ApiResponseListSolicitudResponse>>;
    public listarPorDepartamentoYEstado(nombre: string, estado: 'PENDIENTE' | 'EN_REVISION' | 'APROBADO' | 'RECHAZADO', observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ApiResponseListSolicitudResponse>>;
    public listarPorDepartamentoYEstado(nombre: string, estado: 'PENDIENTE' | 'EN_REVISION' | 'APROBADO' | 'RECHAZADO', observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (nombre === null || nombre === undefined) {
            throw new Error('Required parameter nombre was null or undefined when calling listarPorDepartamentoYEstado.');
        }
        if (estado === null || estado === undefined) {
            throw new Error('Required parameter estado was null or undefined when calling listarPorDepartamentoYEstado.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/workflows/departamento/${this.configuration.encodeParam({name: "nombre", value: nombre, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/estado/${this.configuration.encodeParam({name: "estado", value: estado, in: "path", style: "simple", explode: false, dataType: "'PENDIENTE' | 'EN_REVISION' | 'APROBADO' | 'RECHAZADO'", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ApiResponseListSolicitudResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Mis solicitudes
     * Busca todas las solicitudes iniciadas por un identificador de usuario creador.
     * @endpoint get /api/v1/workflows/usuario/{usuario}
     * @param usuario 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public listarPorUsuario(usuario: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<ApiResponseListSolicitudResponse>;
    public listarPorUsuario(usuario: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ApiResponseListSolicitudResponse>>;
    public listarPorUsuario(usuario: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ApiResponseListSolicitudResponse>>;
    public listarPorUsuario(usuario: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (usuario === null || usuario === undefined) {
            throw new Error('Required parameter usuario was null or undefined when calling listarPorUsuario.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/workflows/usuario/${this.configuration.encodeParam({name: "usuario", value: usuario, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ApiResponseListSolicitudResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Listar todas las solicitudes
     * Obtiene absolutamente todas las solicitudes. Ideal para vista global de Administradores.
     * @endpoint get /api/v1/workflows
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public listarTodas(observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<ApiResponseListSolicitudResponse>;
    public listarTodas(observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ApiResponseListSolicitudResponse>>;
    public listarTodas(observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ApiResponseListSolicitudResponse>>;
    public listarTodas(observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/workflows`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ApiResponseListSolicitudResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Resumen y KPIs
     * Muestra estadisticas sobre cuántas solicitudes hay por cada estado. Útil para Dashboard.
     * @endpoint get /api/v1/workflows/estadisticas
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public obtenerEstadisticas(observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<ApiResponseMapStringObject>;
    public obtenerEstadisticas(observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ApiResponseMapStringObject>>;
    public obtenerEstadisticas(observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ApiResponseMapStringObject>>;
    public obtenerEstadisticas(observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/workflows/estadisticas`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ApiResponseMapStringObject>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Buscar solicitud por código
     * Busca una solicitud usando su código de seguimiento generado aleatoriamente (ej. WF-12345).
     * @endpoint get /api/v1/workflows/seguimiento/{codigo}
     * @param codigo 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public obtenerPorCodigo(codigo: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<ApiResponseSolicitudResponse>;
    public obtenerPorCodigo(codigo: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ApiResponseSolicitudResponse>>;
    public obtenerPorCodigo(codigo: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ApiResponseSolicitudResponse>>;
    public obtenerPorCodigo(codigo: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (codigo === null || codigo === undefined) {
            throw new Error('Required parameter codigo was null or undefined when calling obtenerPorCodigo.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/workflows/seguimiento/${this.configuration.encodeParam({name: "codigo", value: codigo, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ApiResponseSolicitudResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Obtener por ID interno
     * Recuperar los detalles de una solicitud específica basándose en su ID de MongoDB.
     * @endpoint get /api/v1/workflows/{id}
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public obtenerPorId(id: string, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<ApiResponseSolicitudResponse>;
    public obtenerPorId(id: string, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ApiResponseSolicitudResponse>>;
    public obtenerPorId(id: string, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ApiResponseSolicitudResponse>>;
    public obtenerPorId(id: string, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling obtenerPorId.');
        }

        let localVarHeaders = this.defaultHeaders;

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/workflows/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ApiResponseSolicitudResponse>('get', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Reasignar de departamento
     * El administrador puede transferir una solicitud a otro departamento registrando esto en el historial.
     * @endpoint patch /api/v1/workflows/{id}/departamento
     * @param id 
     * @param reasignarDepartamentoRequest 
     * @param xUsuario 
     * @param xRol 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     * @param options additional options
     */
    public reasignarDepartamento(id: string, reasignarDepartamentoRequest: ReasignarDepartamentoRequest, xUsuario?: string, xRol?: 'SOLICITANTE' | 'REVISOR' | 'ADMINISTRADOR', observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<ApiResponseSolicitudResponse>;
    public reasignarDepartamento(id: string, reasignarDepartamentoRequest: ReasignarDepartamentoRequest, xUsuario?: string, xRol?: 'SOLICITANTE' | 'REVISOR' | 'ADMINISTRADOR', observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<ApiResponseSolicitudResponse>>;
    public reasignarDepartamento(id: string, reasignarDepartamentoRequest: ReasignarDepartamentoRequest, xUsuario?: string, xRol?: 'SOLICITANTE' | 'REVISOR' | 'ADMINISTRADOR', observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<ApiResponseSolicitudResponse>>;
    public reasignarDepartamento(id: string, reasignarDepartamentoRequest: ReasignarDepartamentoRequest, xUsuario?: string, xRol?: 'SOLICITANTE' | 'REVISOR' | 'ADMINISTRADOR', observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: '*/*', context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling reasignarDepartamento.');
        }
        if (reasignarDepartamentoRequest === null || reasignarDepartamentoRequest === undefined) {
            throw new Error('Required parameter reasignarDepartamentoRequest was null or undefined when calling reasignarDepartamento.');
        }

        let localVarHeaders = this.defaultHeaders;
        if (xUsuario !== undefined && xUsuario !== null) {
            localVarHeaders = localVarHeaders.set('X-Usuario', String(xUsuario));
        }
        if (xRol !== undefined && xRol !== null) {
            localVarHeaders = localVarHeaders.set('X-Rol', String(xRol));
        }

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
            '*/*'
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/v1/workflows/${this.configuration.encodeParam({name: "id", value: id, in: "path", style: "simple", explode: false, dataType: "string", dataFormat: undefined})}/departamento`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<ApiResponseSolicitudResponse>('patch', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: reasignarDepartamentoRequest,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
