/**
 * Workflow Departamental API
 *
 * Contact: soporte@workflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiResponseMapStringObject { 
    exito?: boolean;
    mensaje?: string;
    datos?: { [key: string]: object; };
    timestamp?: string;
    errores?: { [key: string]: Array<string>; };
}

