/**
 * Workflow Departamental API
 *
 * Contact: soporte@workflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthResponse } from './authResponse';


export interface ApiResponseAuthResponse { 
    exito?: boolean;
    mensaje?: string;
    datos?: AuthResponse;
    timestamp?: string;
    errores?: { [key: string]: Array<string>; };
}

