/**
 * Workflow Departamental API
 *
 * Contact: soporte@workflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SolicitudResponse } from './solicitudResponse';


export interface ApiResponseListSolicitudResponse { 
    exito?: boolean;
    mensaje?: string;
    datos?: Array<SolicitudResponse>;
    timestamp?: string;
    errores?: { [key: string]: Array<string>; };
}

