/**
 * Workflow Departamental API
 *
 * Contact: soporte@workflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Solicitud para asignar o reasignar un revisor a una solicitud de Workflow
 */
export interface AsignarUsuarioRequest { 
    /**
     * Identificador del usuario que será responsable de la solicitud
     */
    usuarioAsignado: string;
}

