/**
 * Workflow Departamental API
 *
 * Contact: soporte@workflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Respuesta tras un login o registro exitoso
 */
export interface AuthResponse { 
    /**
     * Token de autenticación simulado o JWT en el futuro
     */
    token?: string;
    /**
     * Nombre de usuario
     */
    username?: string;
    /**
     * Nombre completo del usuario
     */
    nombreCompleto?: string;
    /**
     * Rol del usuario
     */
    rol?: AuthResponse.RolEnum;
    /**
     * Departamento del usuario
     */
    departamento?: string;
}
export namespace AuthResponse {
    export const RolEnum = {
        Solicitante: 'SOLICITANTE',
        Revisor: 'REVISOR',
        Administrador: 'ADMINISTRADOR'
    } as const;
    export type RolEnum = typeof RolEnum[keyof typeof RolEnum];
}


