/**
 * Workflow Departamental API
 *
 * Contact: soporte@workflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CambiarEstadoRequest { 
    nuevoEstado: CambiarEstadoRequest.NuevoEstadoEnum;
    comentario?: string;
    datosFormulario?: { [key: string]: any; };
}
export namespace CambiarEstadoRequest {
    export const NuevoEstadoEnum = {
        Pendiente: 'PENDIENTE',
        EnRevision: 'EN_REVISION',
        Aprobado: 'APROBADO',
        Rechazado: 'RECHAZADO'
    } as const;
    export type NuevoEstadoEnum = typeof NuevoEstadoEnum[keyof typeof NuevoEstadoEnum];
}


