/**
 * Workflow Departamental API
 *
 * Contact: soporte@workflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Respuesta del Asistente IA del Workflow
 */
export interface ChatIAResponse { 
    /**
     * Texto generado por la Inteligencia Artificial
     */
    respuesta?: string;
    /**
     * Timestamp del mensaje generado
     */
    fecha?: string;
    /**
     * Intención detectada por la IA (opcional)
     */
    intencionDetectada?: string;
}

