/**
 * Workflow Departamental API
 *
 * Contact: soporte@workflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Petición del usuario para hablar con el Asistente de IA
 */
export interface ChatIARequest { 
    /**
     * Texto escrito por el usuario solicitando ayuda o información del workflow
     */
    mensaje: string;
    /**
     * Identificador del usuario
     */
    usuarioId: string;
    /**
     * Indica si la IA debe ejecutarse sin herramientas de base de datos para máxima velocidad y ahorro de costos
     */
    sinHerramientas?: boolean;
}

