/**
 * Workflow Departamental API
 *
 * Contact: soporte@workflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EventoHistorialResponse { 
    fecha?: string;
    estadoAnterior?: EventoHistorialResponse.EstadoAnteriorEnum;
    estadoNuevo?: EventoHistorialResponse.EstadoNuevoEnum;
    usuarioResponsable?: string;
    rolUsuario?: string;
    comentario?: string;
}
export namespace EventoHistorialResponse {
    export const EstadoAnteriorEnum = {
        Pendiente: 'PENDIENTE',
        EnRevision: 'EN_REVISION',
        Aprobado: 'APROBADO',
        Rechazado: 'RECHAZADO'
    } as const;
    export type EstadoAnteriorEnum = typeof EstadoAnteriorEnum[keyof typeof EstadoAnteriorEnum];
    export const EstadoNuevoEnum = {
        Pendiente: 'PENDIENTE',
        EnRevision: 'EN_REVISION',
        Aprobado: 'APROBADO',
        Rechazado: 'RECHAZADO'
    } as const;
    export type EstadoNuevoEnum = typeof EstadoNuevoEnum[keyof typeof EstadoNuevoEnum];
}


