/**
 * Workflow Departamental API
 *
 * Contact: soporte@workflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Petición de inicio de sesión
 */
export interface LoginRequest { 
    /**
     * Nombre de usuario
     */
    username: string;
    /**
     * Contraseña en texto plano (solo para pruebas)
     */
    password: string;
}

