/**
 * Workflow Departamental API
 *
 * Contact: soporte@workflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Petición de registro de nuevo usuario
 */
export interface RegisterRequest { 
    /**
     * Nombre de usuario
     */
    username: string;
    /**
     * Contraseña en texto plano
     */
    password: string;
    /**
     * Nombre completo del usuario
     */
    nombreCompleto: string;
    /**
     * Rol del usuario en el sistema
     */
    rol: RegisterRequest.RolEnum;
    /**
     * Departamento al que pertenece (obligatorio para REVISOR o SOLICITANTE en algunos casos)
     */
    departamento?: string;
}
export namespace RegisterRequest {
    export const RolEnum = {
        Solicitante: 'SOLICITANTE',
        Revisor: 'REVISOR',
        Administrador: 'ADMINISTRADOR'
    } as const;
    export type RolEnum = typeof RolEnum[keyof typeof RolEnum];
}


